#!/bin/bash

echo -n "Restarting bulletindistributord... "
killall -9 bulletindistributord 2> /dev/null
echo "done"

declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:return' >&${cydia[0]}"
fi

exit 0
